import { ChangeDetectionStrategy, Component, OnInit, ChangeDetectorRef } from '@angular/core';
import { CommonModule } from '@angular/common';
import { FormBuilder, FormGroup, Validators, ReactiveFormsModule } from "@angular/forms";
import { Router } from "@angular/router";

import { AnimalData } from '../services/animal-data';
import { AnimalIntData } from '../models/animals';

@Component({
  selector: 'app-edit-animal',
  imports: [CommonModule, ReactiveFormsModule],
  templateUrl: './edit-animal.html',
  styleUrl: './edit-animal.css',
})
export class EditAnimal {
  public editForm!: FormGroup;
  animal!: AnimalIntData;
  submitted = false;
  message : string = '';
  record_number: any;
  constructor(
    private formBuilder: FormBuilder,
    private router: Router,
    private AnimalDataService: AnimalData,
    private ref: ChangeDetectorRef
  ) {}

  ngOnInit() : void{
// Retrieve stashed trip ID
    let rec_num = localStorage.getItem("rec_num");
    this.record_number = rec_num;
    if (!rec_num) {
    alert("Something wrong, couldn't find where I stashed record numbers");
    this.router.navigate(['']);
    return;
  }

  //console.log('EditTripComponent::ngOnInit');
  //console.log('rec_num:' + rec_num);

    this.editForm = this.formBuilder.group({
     _id: [], //ID generated by MongoDB
      rec_num: ['', Validators.required],
      age_upon_outcome: ['',  Validators.required],
      animal_id: ['',  Validators.required],
      animal_type: ['',  Validators.required],
      breed: ['',  Validators.required],
      color: ['',  Validators.required],
      date_of_birth: ['',  Validators.required],
      datetime: ['',  Validators.required],
      monthyear: ['',  Validators.required],
      name: ['',  Validators.required],
      outcome_subtype: ['',  Validators.required],
      outcome_type: ['',  Validators.required],
      sex_upon_outcome: ['',  Validators.required],
      location_lat: ['',  Validators.required],
      location_long: ['',  Validators.required],
      age_upon_outcome_in_weeks: ['',  Validators.required],
   })
    this.AnimalDataService.getAnimalsByRecord(rec_num)
    .subscribe({
      next: (value: any) => {
      this.animal = value;
      // Populate our record into the form
      this.editForm.patchValue(value[0]);
      if(!value)
      {
      this.message = 'No Animal Retrieved!';
      } else{
      this.message = 'Animal: ' + rec_num + ' retrieved';
    }
    console.log(this.message);
  },
    error: (error: any) => {
    console.log('Error: ' + error);
    }
    })
  }

  public onSubmit()
  {
    this.submitted = true;
    if(this.editForm.valid)
    {
    this.AnimalDataService.updateAnimal(this.editForm.value)
    .subscribe({
      next: (value: any) => {
      console.log(value);
      this.ref.detectChanges();
      this.router.navigate(['']);
      },
        error: (error: any) => {
        console.log('Error: ' + error);
        }
      })
    }
  }

  // Get Quick access name
  get f() { return this.editForm.controls; }


  //Delete Record
  public deleteRecord(): void{
    //API DELETE CALL
    this.AnimalDataService.removeAnimalByRecord(this.record_number).subscribe({
      next: () => {
      this.ref.detectChanges();
      this.router.navigate(['']);
      },
        error: (error: any) => {
        console.log('Error: ' + error);
        }
      }
    );
  }
}
